[core]
http.port = 8084
http.certFile =
http.keyFile =
[api]
start = true
pprof = false
###不填写的话，则与core共用
[ex]
start = true
liveTime = 4
[log]
file.path = push.log
console.level = debug
write.level = warn
[cluster]
##集群端口，不填写的话，则与core共用
start = true

remote.host = 127.0.0.1:8085
local.port =  8084

machineId :