web:
  server:
    port: 8084
  log:
    level: debug
    file_path: push.log

cluster:
  start: true
  local_port: 8085
  machine_id: ""

ex:
  start: true
  live_time: 15

ws:
  start: true
  openSend: false

api:
  start: true

