// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: cluster/cluster.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Initial 握手
type InitialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       []byte                 `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"` // JSON-encoded Machine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialRequest) Reset() {
	*x = InitialRequest{}
	mi := &file_cluster_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialRequest) ProtoMessage() {}

func (x *InitialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialRequest.ProtoReflect.Descriptor instead.
func (*InitialRequest) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *InitialRequest) GetMachine() []byte {
	if x != nil {
		return x.Machine
	}
	return nil
}

type InitialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       []byte                 `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"` // JSON-encoded Machine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialResponse) Reset() {
	*x = InitialResponse{}
	mi := &file_cluster_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialResponse) ProtoMessage() {}

func (x *InitialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialResponse.ProtoReflect.Descriptor instead.
func (*InitialResponse) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *InitialResponse) GetMachine() []byte {
	if x != nil {
		return x.Machine
	}
	return nil
}

// QueryMachineList 查询节点列表
type QueryMachineListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       []byte                 `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"` // JSON-encoded Machine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMachineListRequest) Reset() {
	*x = QueryMachineListRequest{}
	mi := &file_cluster_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMachineListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMachineListRequest) ProtoMessage() {}

func (x *QueryMachineListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMachineListRequest.ProtoReflect.Descriptor instead.
func (*QueryMachineListRequest) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *QueryMachineListRequest) GetMachine() []byte {
	if x != nil {
		return x.Machine
	}
	return nil
}

type QueryMachineListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machines      []byte                 `protobuf:"bytes,1,opt,name=machines,proto3" json:"machines,omitempty"` // JSON-encoded []*Machine
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMachineListResponse) Reset() {
	*x = QueryMachineListResponse{}
	mi := &file_cluster_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMachineListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMachineListResponse) ProtoMessage() {}

func (x *QueryMachineListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMachineListResponse.ProtoReflect.Descriptor instead.
func (*QueryMachineListResponse) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *QueryMachineListResponse) GetMachines() []byte {
	if x != nil {
		return x.Machines
	}
	return nil
}

// Query 通用查询转发
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameter     []byte                 `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"` // JSON-encoded core.Parameter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_cluster_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetParameter() []byte {
	if x != nil {
		return x.Parameter
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // JSON-encoded query result, 空表示无结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_cluster_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

// SendTextMsg 转发消息
type SendTextMsgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // JSON-encoded message.TextMessage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextMsgRequest) Reset() {
	*x = SendTextMsgRequest{}
	mi := &file_cluster_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextMsgRequest) ProtoMessage() {}

func (x *SendTextMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextMsgRequest.ProtoReflect.Descriptor instead.
func (*SendTextMsgRequest) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *SendTextMsgRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendTextMsgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextMsgResponse) Reset() {
	*x = SendTextMsgResponse{}
	mi := &file_cluster_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextMsgResponse) ProtoMessage() {}

func (x *SendTextMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextMsgResponse.ProtoReflect.Descriptor instead.
func (*SendTextMsgResponse) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *SendTextMsgResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendTextMsgResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_cluster_cluster_proto protoreflect.FileDescriptor

const file_cluster_cluster_proto_rawDesc = "" +
	"\n" +
	"\x15cluster/cluster.proto\x12\acluster\"*\n" +
	"\x0eInitialRequest\x12\x18\n" +
	"\amachine\x18\x01 \x01(\fR\amachine\"+\n" +
	"\x0fInitialResponse\x12\x18\n" +
	"\amachine\x18\x01 \x01(\fR\amachine\"3\n" +
	"\x17QueryMachineListRequest\x12\x18\n" +
	"\amachine\x18\x01 \x01(\fR\amachine\"6\n" +
	"\x18QueryMachineListResponse\x12\x1a\n" +
	"\bmachines\x18\x01 \x01(\fR\bmachines\",\n" +
	"\fQueryRequest\x12\x1c\n" +
	"\tparameter\x18\x01 \x01(\fR\tparameter\"'\n" +
	"\rQueryResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\".\n" +
	"\x12SendTextMsgRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"?\n" +
	"\x13SendTextMsgResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xa2\x02\n" +
	"\aCluster\x12<\n" +
	"\aInitial\x12\x17.cluster.InitialRequest\x1a\x18.cluster.InitialResponse\x12W\n" +
	"\x10QueryMachineList\x12 .cluster.QueryMachineListRequest\x1a!.cluster.QueryMachineListResponse\x126\n" +
	"\x05Query\x12\x15.cluster.QueryRequest\x1a\x16.cluster.QueryResponse\x12H\n" +
	"\vSendTextMsg\x12\x1b.cluster.SendTextMsgRequest\x1a\x1c.cluster.SendTextMsgResponseB$Z\"github.com/chuccp/httpPush/clusterb\x06proto3"

var (
	file_cluster_cluster_proto_rawDescOnce sync.Once
	file_cluster_cluster_proto_rawDescData []byte
)

func file_cluster_cluster_proto_rawDescGZIP() []byte {
	file_cluster_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_cluster_proto_rawDesc), len(file_cluster_cluster_proto_rawDesc)))
	})
	return file_cluster_cluster_proto_rawDescData
}

var file_cluster_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cluster_cluster_proto_goTypes = []any{
	(*InitialRequest)(nil),           // 0: cluster.InitialRequest
	(*InitialResponse)(nil),          // 1: cluster.InitialResponse
	(*QueryMachineListRequest)(nil),  // 2: cluster.QueryMachineListRequest
	(*QueryMachineListResponse)(nil), // 3: cluster.QueryMachineListResponse
	(*QueryRequest)(nil),             // 4: cluster.QueryRequest
	(*QueryResponse)(nil),            // 5: cluster.QueryResponse
	(*SendTextMsgRequest)(nil),       // 6: cluster.SendTextMsgRequest
	(*SendTextMsgResponse)(nil),      // 7: cluster.SendTextMsgResponse
}
var file_cluster_cluster_proto_depIdxs = []int32{
	0, // 0: cluster.Cluster.Initial:input_type -> cluster.InitialRequest
	2, // 1: cluster.Cluster.QueryMachineList:input_type -> cluster.QueryMachineListRequest
	4, // 2: cluster.Cluster.Query:input_type -> cluster.QueryRequest
	6, // 3: cluster.Cluster.SendTextMsg:input_type -> cluster.SendTextMsgRequest
	1, // 4: cluster.Cluster.Initial:output_type -> cluster.InitialResponse
	3, // 5: cluster.Cluster.QueryMachineList:output_type -> cluster.QueryMachineListResponse
	5, // 6: cluster.Cluster.Query:output_type -> cluster.QueryResponse
	7, // 7: cluster.Cluster.SendTextMsg:output_type -> cluster.SendTextMsgResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cluster_cluster_proto_init() }
func file_cluster_cluster_proto_init() {
	if File_cluster_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_cluster_proto_rawDesc), len(file_cluster_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_cluster_proto_depIdxs,
		MessageInfos:      file_cluster_cluster_proto_msgTypes,
	}.Build()
	File_cluster_cluster_proto = out.File
	file_cluster_cluster_proto_goTypes = nil
	file_cluster_cluster_proto_depIdxs = nil
}
